//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class EEPoseMsg : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/EEPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose_pos;
        public Geometry.PoseMsg pose_vel;

        public EEPoseMsg()
        {
            this.pose_pos = new Geometry.PoseMsg();
            this.pose_vel = new Geometry.PoseMsg();
        }

        public EEPoseMsg(Geometry.PoseMsg pose_pos, Geometry.PoseMsg pose_vel)
        {
            this.pose_pos = pose_pos;
            this.pose_vel = pose_vel;
        }

        public static EEPoseMsg Deserialize(MessageDeserializer deserializer) => new EEPoseMsg(deserializer);

        private EEPoseMsg(MessageDeserializer deserializer)
        {
            this.pose_pos = Geometry.PoseMsg.Deserialize(deserializer);
            this.pose_vel = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_pos);
            serializer.Write(this.pose_vel);
        }

        public override string ToString()
        {
            return "EEPoseMsg: " +
            "\npose_pos: " + pose_pos.ToString() +
            "\npose_vel: " + pose_vel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
